import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, Calendar, UserCircle } from 'lucide-react';
import { useBlog } from '../hooks/useBlogData'; // <-- Use the Firebase hook instead of static data

export default function BlogDetail() {
  const { id } = useParams();
  const { blog, loading, error } = useBlog(id); // <-- Fetch from backend

  // 1. Loading State
  if (loading) {
    return (
      <div className="flex justify-center items-center py-32">
        <div className="w-8 h-8 border-4 border-brand-blue border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  // 2. Error / Not Found State
  if (error || !blog) {
    return (
      <div className="section-container py-24 text-center">
        <h1 className="text-3xl font-bold mb-4">Post not found</h1>
        <p className="text-brand-gray mb-6">{error || "This article may have been moved or deleted."}</p>
        <Link to="/blog" className="btn-primary inline-block">Back to Blog</Link>
      </div>
    );
  }

  // 3. Success State - Render the Blog
  return (
    <div className="bg-white">
      {/* Hero Image */}
      <div className="h-[40vh] md:h-[50vh] w-full relative overflow-hidden bg-gray-100">
        <img 
          src={blog.image} 
          alt={blog.title} 
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
      </div>

      <article className="section-container max-w-3xl mx-auto py-12 md:py-16">
        <Link to="/blog" className="inline-flex items-center gap-2 text-brand-gray hover:text-brand-blue mb-8 transition-colors">
          <ArrowLeft size={16} /> Back to Blog
        </Link>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="text-3xl md:text-5xl font-extrabold text-brand-dark leading-tight mb-6">
            {blog.title}
          </h1>
          
          <div className="flex items-center gap-6 text-sm text-brand-gray mb-10 pb-10 border-b border-brand-border">
            <div className="flex items-center gap-2">
              <UserCircle size={18} />
              {blog.author}
            </div>
            <div className="flex items-center gap-2">
              <Calendar size={18} />
              {blog.date}
            </div>
          </div>

          {/* Rich Text Content Container */}
          {/* The arbitrary Tailwind classes [&_tag]:... ensure that whatever HTML 
              the React Quill editor generates matches your brand design system perfectly */}
          <div className="max-w-none text-brand-dark/80 leading-relaxed space-y-6
                        [&_h1]:text-3xl [&_h1]:font-bold [&_h1]:text-brand-dark [&_h1]:mt-8 [&_h1]:mb-4
                        [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:text-brand-dark [&_h2]:mt-6 [&_h2]:mb-3
                        [&_h3]:text-xl [&_h3]:font-bold [&_h3]:text-brand-dark [&_h3]:mt-4 [&_h3]:mb-2
                        [&_p]:text-brand-gray [&_p]:leading-relaxed [&_p]:mb-4
                        [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2 [&_ul]:text-brand-gray
                        [&_ol]:list-decimal [&_ol]:pl-6 [&_ol]:space-y-2 [&_ol]:text-brand-gray
                        [&_li]:mb-1
                        [&_strong]:font-bold [&_strong]:text-brand-dark
                        [&_a]:text-brand-blue [&_a]:underline
                        [&_blockquote]:border-l-4 [&_blockquote]:border-brand-blue [&_blockquote]:pl-4 [&_blockquote]:italic [&_blockquote]:text-gray-600
                        [&_img]:rounded-xl [&_img]:shadow-md [&_img]:my-6 [&_img]:max-w-full [&_img]:mx-auto">
            
            {/* Show the excerpt distinctly */}
            <p className="text-xl font-medium text-brand-dark mb-4">{blog.excerpt}</p>
            
            {/* Safely render the HTML string generated by React Quill */}
            <div dangerouslySetInnerHTML={{ __html: blog.content }} />
          </div>
        </motion.div>
      </article>
    </div>
  );
}
